version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: tg_postgres
    restart: always
    environment:
      POSTGRES_USER: tg_user
      POSTGRES_PASSWORD: tg_password
      POSTGRES_DB: tg_database
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
